/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d8e3fa",
        "surface-container-high": "#dee8ff",
        "surface": "#f9f9ff",
        "on-primary-fixed": "#0d1c32",
        "on-secondary-container": "#785a1a",
        "error-container": "#ffdad6",
        "on-surface": "#111c2c",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#454748",
        "tertiary-fixed-dim": "#c5c7c8",
        "surface-tint": "#515f78",
        "on-secondary-fixed": "#261900",
        "surface-bright": "#f9f9ff",
        "tertiary-container": "#191c1d",
        "background": "#f9f9ff",
        "on-surface-variant": "#44474d",
        "on-primary-container": "#76849f",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b9c7e4",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#000000",
        "surface-container": "#e7eeff",
        "surface-container-low": "#f0f3ff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdea5",
        "outline": "#75777e",
        "on-secondary-fixed-variant": "#5d4201",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e9c176",
        "inverse-primary": "#b9c7e4",
        "primary": "#000000",
        "outline-variant": "#c5c6cd",
        "inverse-surface": "#263142",
        "on-tertiary-fixed": "#191c1d",
        "surface-dim": "#cfdaf1",
        "secondary": "#775a19",
        "secondary-container": "#fed488",
        "primary-container": "#0d1c32",
        "primary-fixed": "#d6e3ff",
        "on-primary-fixed-variant": "#39475f",
        "on-tertiary-container": "#828485",
        "inverse-on-surface": "#ebf1ff",
        "surface-container-highest": "#d8e3fa",
        "tertiary-fixed": "#e1e3e4",
        "on-background": "#111c2c",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "md": "24px",
        "gutter": "24px",
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "lg": "40px",
        "margin-desktop": "48px",
        "xl": "64px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Libre Caslon Text", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Libre Caslon Text", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Libre Caslon Text", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
